<main class="main">
    <div class="slider">
        <div class="slides">
            <img src="../images/banner.jpg" class="slide" alt="">
            <img src="../images/book2.jpg" class="slide" alt="">
            <img src="../images/book3.jpg" class="slide" alt="">
            <img src="../images/example.jpg" class="slide" alt="">
        </div>
        <div class="dots">
            <!-- Dots will be generated by JavaScript  -->
        </div>
    </div>

    <div class="section-about">

    </div>
    <div class="section">
        <div class="title-category w85 m0">
            <span>SÁCH MỚI</span>
        </div>
        <div class="product-nav">
            <div class="prev">
                <i class="fa-solid fa-chevron-left"></i>
            </div>
            <div class="next">
                <i class="fa-solid fa-chevron-right"></i>
            </div>
        </div>
        <div class="product-grid nowrap grid-5">
            <?php include_once '../controller/BookController.php';
            $bookController = new BookController();
            $category_id = 1;
            $books = $bookController->getBooksByCategory($category_id);
            if (isset($books) && is_array($books)) {
                foreach ($books as $book) {
                    echo '<div class="book-item">
                            <img src="../images/' . $book['image'] . '" alt="">
                            <h3 class="ellipsis">' . $book['title'] . '</h3>
                            <p>' . number_format($book['price'], 0, '', '.') . ' VND</p>
                            <form action="../controller/BookController.php" method="post">
                                <input type="hidden" name="anhsp" value="' . $book['image'] . '">
                                <input type="hidden" name="tensp" value="' . $book['title'] . '">
                                <input type="hidden" name="gia" value="' . $book['price'] . '">
                                <input type="submit" name="addcart" value="Đặt hàng" class="add-to-cart">
                            </form>
                        </div>';
                }
            } else {
                echo 'Không có sách nào trong danh sách.';
            }
            ?>
            <!-- Repeat book-item for other books -->
        </div>
    </div>
    <div class="section-banner w85">
        <img src="../images/banner.jpg" alt="">
    </div>
    <div class="section">
        <div class="title-category w85 m0">
            <span>SÁCH MỚI</span>
        </div>
        <div class="product-nav">
            <div class="prev">
                <i class="fa-solid fa-chevron-left"></i>
            </div>
            <div class="next">
                <i class="fa-solid fa-chevron-right"></i>
            </div>
        </div>
        <div class="product-grid nowrap grid-5">
            <?php include_once '../controller/BookController.php';
            $bookController = new BookController();
            $category_id = 2;
            $books = $bookController->getBooksByCategory($category_id);
            if (isset($books) && is_array($books)) {
                foreach ($books as $book) {
                    echo '<div class="book-item">
                            <img src="../images/' . $book['image'] . '" alt="">
                            <h3 class="ellipsis">' . $book['title'] . '</h3>
                            <p>' . number_format($book['price'], 0, '', '.') . ' VND</p>
                            <form action="../controller/BookController.php" method="post">
                                <input type="hidden" name="anhsp" value="' . $book['image'] . '">
                                <input type="hidden" name="tensp" value="' . $book['title'] . '">
                                <input type="hidden" name="gia" value="' . $book['price'] . '">
                                <input type="submit" name="addcart" value="Đặt hàng" class="add-to-cart">
                            </form>
                        </div>';
                }
            } else {
                echo 'Không có sách nào trong danh sách.';
            }
            ?>
            <!-- Repeat book-item for other books -->
        </div>
    </div>
</main>